# ############################################################################
# Model: E2E ASR with attention-based ASR
# Training data: FINNISH PARLIAMENT (First release) 30min/spk subset
# Encoder: CRDNN
# Decoder: GRU + beamsearch + RNNLM
# Authors: Aku Rouhe 2021 
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are instantiated
seed: 2602
__set_seed: !apply:torch.manual_seed [!ref <seed>]

trainshards: !apply:glob.glob ["./shards/train_all_sub2/shard-000*.tar"]
validshards: !apply:glob.glob ["./shards/dev_2k_sub2/shard-000*.tar"]
# data_folder_rirs: ./augmentation_data # noise/ris dataset will automatically be downloaded here
num_units: 5000
output_folder: !ref exp/attention/mwer/W2V2-A/<seed>-<num_units>units
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
tokenizer_path: !ref exp/lm/train_varikn.bpe<num_units>.d0.0001/bpe.<num_units>.model

tokenizer: !new:sentencepiece.SentencePieceProcessor
    model_file: !ref <tokenizer_path>

pretraining_from: !ref exp/attention/W2V2-A/<seed>-<num_units>units/save

# wav2vec 2.0 
w2v2_savepath: ./w2v2_checkpoints
wav2vec2_hub: facebook/wav2vec2-large-uralic-voxpopuli-v2

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

subsampling: 4

grad_accumulation_factor: 4

# Training parameters
number_of_epochs: 25
number_of_ctc_epochs: -1
train_dynamic_batcher: !name:speechbrain.dataio.iterators.dynamic_bucketed_batch
    max_sample_len: !ref <sample_rate> * 90
    sampler_kwargs:
        target_batch_numel: !ref <sample_rate> * 180 / <grad_accumulation_factor> # 16000*120=2minutes
        max_batch_numel: !ref <sample_rate> * 200 / <grad_accumulation_factor>
    len_key: 'wav'
train_loader_kwargs:
    num_workers: 4
    looped_nominal_epoch: !ref 1000 * <grad_accumulation_factor>
    batch_size: null
valid_dynamic_batcher: !name:speechbrain.dataio.iterators.dynamic_bucketed_batch
    len_key: "wav"
    sampler_kwargs:
        target_batch_numel: !ref <sample_rate> * 200
        max_batch_numel: !ref <sample_rate> * 220
    max_sample_len: !ref <sample_rate> * 25
    drop_end: False
validbatchsize: 4
ctc_weight: 0.5
ckpt_interval_minutes: 30 # save checkpoint every N min
label_smoothing: 0.1
lr: 0.000001
lr_wav2vec: 0.0001

# MWER params:
nll_weight: 0.01
topk: 12
sampler_beam_size: 12
subtract_avg: True
mwer_pad_index: 0
minwertype: TrueWER


# Model parameters
activation: !name:torch.nn.LeakyReLU
wav2vec_output_dim: 1024
dnn_neurons: 1024
freeze_wav2vec: True
dropout: 0.15

emb_size: 128
dec_neurons: 1024
dec_layers: 1
output_neurons: !ref <num_units>  #Number of tokens (same as LM)

unk_index: 0 
blank_index: 0
pad_index: 0
bos_index: 1
eos_index: 2

# Decoding parameters
test_data_dir: "valid"
test_data_id: "valid"
min_decode_ratio: 0.0
max_decode_ratio: 1.0
valid_beam_size: 4
test_beam_size: 4
eos_threshold: 1.3
using_max_attn_shift: False
max_attn_shift: 240
ctc_weight_decode: 0.5
coverage_penalty: 3.0 
temperature: 2.0
wer_file: !ref <output_folder>/wer_<test_data_id>_beam<test_beam_size>_cov<coverage_penalty>_eos<eos_threshold>_temp<temperature>_noattnshift.txt
decode_text_file: !ref <output_folder>/text_<test_data_id>_beam<test_beam_size>_cov<coverage_penalty>_eos<eos_threshold>_temp<temperature>_noattnshift.txt

# The first object passed to the Brain class is this "Epoch Counter"
# which is saved by the Checkpointer so that training can be resumed
# if it gets interrupted at any point.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>


wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: !ref <freeze_wav2vec>
    freeze_feature_extractor: True
    save_path: !ref <w2v2_savepath>

enc: !new:speechbrain.nnet.containers.Sequential
    input_shape: [null, null, !ref <wav2vec_output_dim>]
    linear1: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <dnn_neurons>
        bias: True
    bn1: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation: !new:torch.nn.LeakyReLU
    drop: !new:torch.nn.Dropout
        p: !ref <dropout>
    linear2: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <dnn_neurons>
        bias: True
    bn2: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation2: !new:torch.nn.LeakyReLU

# Embedding (from indexes to an embedding space of dimension emb_size).
embedding: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

# Attention-based RNN decoder.
decoder: !new:local_RNN.AttentionalRNNDecoder
    enc_dim: !ref <dnn_neurons>
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: !ref <dec_neurons>
    attn_dim: 2048
    num_layers: !ref <dec_layers>
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: !ref <dropout>

# Linear transformation on the top of the encoder.
ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <wav2vec_output_dim>
    n_neurons: !ref <output_neurons>

# Linear transformation on the top of the decoder.
seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dec_neurons>
    n_neurons: !ref <output_neurons>

# Final softmax (for log posteriors computation).
log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

# Cost definition for the CTC part.
ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

# Objects in "modules" dict will have their parameters moved to the correct
# device, as well as having train()/eval() called on them by the Brain class
modules:
    wav2vec2: !ref <wav2vec2>
    encoder: !ref <enc>
    embedding: !ref <embedding>
    decoder: !ref <decoder>
    ctc_lin: !ref <ctc_lin>
    seq_lin: !ref <seq_lin>

# Gathering all the submodels in a single model object.
model: !new:torch.nn.ModuleList
    - [!ref <embedding>, !ref <ctc_lin>, !ref <seq_lin>, !ref <decoder>, !ref <enc>]

# Beamsearch is applied on the top of the decoder. If the language model is
# given, a language model is applied (with a weight specified in lm_weight).
# If ctc_weight is set, the decoder uses CTC + attention beamsearch. This
# improves the performance, but slows down decoding. For a description of
# the other parameters, please see the speechbrain.decoders.S2SRNNBeamSearchLM.

# It makes sense to have a lighter search during validation. In this case,
# we don't use the LM and CTC probabilities during decoding.
greedy_search: !new:speechbrain.decoders.S2SRNNGreedySearcher
    embedding: !ref <embedding>
    decoder: !ref <decoder>
    linear: !ref <seq_lin>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    
    
valid_search: !new:speechbrain.decoders.S2SRNNBeamSearcher
    embedding: !ref <embedding>
    decoder: !ref <decoder>
    linear: !ref <seq_lin>
    ctc_linear: !ref <ctc_lin>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    blank_index: !ref <blank_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <valid_beam_size>
    eos_threshold: !ref <eos_threshold>
    using_max_attn_shift: !ref <using_max_attn_shift>
    max_attn_shift: !ref <max_attn_shift>
    coverage_penalty: !ref <coverage_penalty>
    ctc_weight: !ref <ctc_weight_decode>
    temperature: !ref <temperature>

# The final decoding on the test set can be more computationally demanding.
# In this case, we use the LM + CTC probabilities during decoding as well.
# Please, remove this part if you need a faster decoder.
test_search: !new:speechbrain.decoders.S2SRNNBeamSearcher
    embedding: !ref <embedding>
    decoder: !ref <decoder>
    linear: !ref <seq_lin>
    ctc_linear: !ref <ctc_lin>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    blank_index: !ref <blank_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <test_beam_size>
    eos_threshold: !ref <eos_threshold>
    using_max_attn_shift: !ref <using_max_attn_shift>
    max_attn_shift: !ref <max_attn_shift>
    coverage_penalty: !ref <coverage_penalty>
    ctc_weight: !ref <ctc_weight_decode>
    temperature: !ref <temperature>

sampler: !new:local_decoders.S2SRNNBeamSearcher
   embedding: !ref <embedding>
   decoder: !ref <decoder>
   linear: !ref <seq_lin>
   bos_index: !ref <bos_index>
   eos_index: !ref <eos_index>
   topk: !ref <topk>
   min_decode_ratio: !ref <min_decode_ratio>
   max_decode_ratio: !ref <max_decode_ratio>
   beam_size: !ref <sampler_beam_size>
   eos_threshold: !ref <eos_threshold>
   coverage_penalty: !ref <coverage_penalty>
   using_eos_threshold: False
   length_normalization: False
   using_max_attn_shift: False

lr_annealing_model: !new:local.NoSchedule
    lr: !ref <lr>

lr_annealing_wav2vec: !new:local.NoSchedule
    lr: !ref <lr>

model_opt_class: !name:torch.optim.Adam
      lr: !ref <lr> 

wav2vec_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec>

# Functions that compute the statistics to track during the validation step.
error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

# This object is used for saving the state of training both so that it
# can be resumed if it gets interrupted, and also so that the best checkpoint
# can be later loaded for evaluation or inference.
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        wav2vec2: !ref <wav2vec2>
        model: !ref <model>
        counter: !ref <epoch_counter>
        encoder: !ref <enc>

ckpt_finder: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <pretraining_from>

ckpt_finder_kwargs:
    max_key: unixtime

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <output_folder>/pretraining-files
    loadables:
        wav2vec2: !ref <wav2vec2>
        model: !ref <model>
        encoder: !ref <enc>
